/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lenovo' at '17/9/16 6:17 PM' with Gradle 2.14.1
 *
 * @author lenovo, @date 17/9/16 6:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
